name: mapkit_samples
description: "Flutter Demo App for Yandex Mapkit SDK"
publish_to: 'none'
version: 0.0.1

environment:
  sdk: '>=3.2.6 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  map_objects:
    path: map_objects
  map_with_jams:
    path: map_with_jams
  map_with_user_placemark:
    path: map_with_user_placemark
  map_routing:
    path: map_routing
  map_search:
    path: map_search
  map_with_custom_style:
    path: map_with_custom_style
  map_offline:
    path: map_offline

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
